[32m2025-01-21 10:47:37 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 3ed0927e-7e91-4838-ac98-6cae2b7dae31 - 463905 - LOGS_CAPTURED - Started capturing logs in process (pid: 463905).
[32m2025-01-21 10:47:38 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 3ed0927e-7e91-4838-ac98-6cae2b7dae31 - 463905 - fetch_daily_weather - STEP_START - Started execution of step "fetch_daily_weather".
INFO:alembic.runtime.migration:Context impl SQLiteImpl.
INFO:alembic.runtime.migration:Will assume non-transactional DDL.
INFO:weather_project.assets:Fetching daily average weather for Pune...
INFO:alembic.runtime.migration:Context impl SQLiteImpl.
INFO:alembic.runtime.migration:Will assume non-transactional DDL.
INFO:alembic.runtime.migration:Running stamp_revision  -> 6b7fb194ff9c
INFO:alembic.runtime.migration:Context impl SQLiteImpl.
INFO:alembic.runtime.migration:Will assume non-transactional DDL.
INFO:alembic.runtime.migration:Running stamp_revision  -> 6b7fb194ff9c
[32m2025-01-21 10:47:38 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 3ed0927e-7e91-4838-ac98-6cae2b7dae31 - 463905 - fetch_daily_weather - STEP_FAILURE - Execution of step "fetch_daily_weather" failed.

dagster._core.errors.DagsterInvalidInvocationError: Too many input arguments were provided for op 'fetch_weather'. This may be because you attempted to provide a value for a nothing dependency. Nothing dependencies are ignored when directly invoking ops.

Stack Trace:
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 245, in dagster_event_sequence_for_step
    yield from check.generator(step_events)
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 501, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 184, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 88, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 190, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 159, in _yield_compute_results
    for event in iterate_with_context(
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/mnt/h/wsl_dagster/weather_project/weather_project/assets.py", line 66, in fetch_daily_weather
    weather_df = fetch_weather(city)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/definitions/assets.py", line 400, in __call__
    return direct_invocation_result(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/definitions/op_invocation.py", line 214, in direct_invocation_result
    input_dict = _resolve_inputs(op_def, input_args, input_kwargs, bound_context)  # type: ignore # (pyright bug)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user_123/dagster_env/lib/python3.12/site-packages/dagster/_core/definitions/op_invocation.py", line 272, in _resolve_inputs
    raise DagsterInvalidInvocationError(
[0m
